[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "hfs3"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
huggingface_hub = "*"
aiohttp = "*"
aiobotocore = "*"
rich = "*"
typer = "*"
tenacity = "*"
hatchling = "*"

[pypi-dependencies]
hfs3 = { path = ".", editable = true }

[activation.env]
HF_XET_HIGH_PERFORMANCE = "1"
HF_XET_NUM_CONCURRENT_RANGE_GETS = "32"
