[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "hfs3"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
huggingface_hub = "*"
s3fs = "*"
rich = "*"
typer = "*"
hatchling = "*"

[pypi-dependencies]
hfs3 = { path = ".", editable = true }
